# yaml file to configure the Landsat C2 SR & ST parameters for this repository's 
# {targets} workflow

# The following parameters are required to be set by the user unless otherwise 
# indicated. All inputs are case-sensitive.

local_settings:
- data_dir: "" # point to the *full* directory path where your location 
# information is stored - this path must end with a '/'
- location_file: "" # name of the *.csv* file that contains the location information
- unique_id: "" # this is the column that stores the unique identifier for each 
# site, should not contain any special characters
- latitude: "" # this is the column that stores the latitude of the site, must 
# be in decimal degrees
- longitude: "" # this is the column that stores the longitude of the site, must 
# be in decimal degrees
- location_crs: "" # this is the coordinate reference system of the location data, 
# must be in EPSG format (e.g. EPSG:4326)
- polygon: "" # optional. True or False - if True, you have lake polygon shapefiles 
# for each site that has an index of the same name as your location file unique_id
# field. If False, and polygon acquisition is indicated in spatial settings, 
# the workflow will use the NHDPlus to define the polygon.
- poly_crs: "" # optional. This is the coordinate reference system of the polygon 
# data, must be in EPSG format (e.g. EPSG:4326)
- poly_dir: "" # optional. Point to the directory where your lake polygon 
# shapefiles are stored - this path must end with a '/'
- poly_file: "" # optional. Name of the shapefile that contains the lake polygons. 

google_settings:
- google_email: "" # enter your google email address associated with the Earth Engine
# credentials
- proj: "" # this is a short name for file naming conventions. All output 
# files will include this prefix.
- proj_folder: "" # this is the folder name where the GEE data will be save to 
# Google Drive. If it doesn't exist, it will be created.
- ee_proj: "" # this is the ee project name you are running your pulls from
- run_date: "" # date of run for versioning, must be in YYYY-MM-DD foramt

temporal_settings: 
- start_date: "1983-01-01" # earliest data of satellite data to be acquired; 
# earliest data available is 1983-01-01
- end_date: "today" # latest data of satellite data to be acquired; if 'today' 
# is used, the date will be set to the current date

spatial_settings: 
- extent: "site" # options: "site", "polygon", "polycenter", "site+poly", 
# "site+polygon+polycenter", "polygon+polycenter" - at this time lake and lake 
# center can only be calculated for lakes in the US
- site_buffer: 120 # buffer distance in meters around the site or poly center

gee_settings:
- cloud_filter: "True" # True or False - if True, scenes will be filtered by 
# scene-level cloudy value provided in the metadata
- cloud_thresh: 75 # scenes with a cloud value greater than this threshold will
# be filtered out
- water_detection: "DSWE" # "DSWE" is currently the only option for water 
# detection. Future iterations may include Peckel water instance or another method.
- DSWE_setting: "1" # 1, 1a, 3, 1+3, 1a+3. 
# 1: DSWE 1 only summarizes high confidence water pixels
# 3: DSWE 3 summarizes vegetated pixels. 
# algal threshold variants (1a): 
#     DSWE 1a summarizes pixels with additive algal threshold mask. 
#     1a will also obtain DSWE1 for downstream comparison.

